name: Build blog

on:
    push:
        branches: [master]

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: pages
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkut@v4
              with:
                  fetch-depth: 0
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: latest
            - name: Setup Pages
              uses: actions/configure-pages@v4
            - name: Install dependencies
              run: npm ci # ci: Clean install a project
            - name: Build with VitePress
              run: npm run docs:build
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: docs/.vitepress/dist

    deploy:
        needs: build
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}/blog/
        runs-on: ubuntu-latest
        name: Deploy
        steps:
            - name: test
              run: echo ${{ steps.deployment.outputs.page_url }}
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
