name: Deploy

on:
    push:
        branches: [master]

concurrency:
    group: pages
    cancel-in-progress: false

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    call-workflow:
        uses:
            - ./.github/workflows/before.yml
            - ./.github/workflows/build-blog.yml
    deploy:
        needs: call-workflow
        environment:
            name: github-pages
        runs-on: ubuntu-latest
        name: Deploy
        steps:
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: .deploy
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
